export const chapters = [
    { title: "Chapter 1", desc: "The journey begins with an unexpected twist." },
    { title: "Chapter 2", desc: "Secrets of the ancient ruins are unveiled." },
    { title: "Chapter 3", desc: "A dangerous ally joins the party." },
    { title: "Chapter 4", desc: "An ambush in the dark forest." },
    { title: "Chapter 5", desc: "The mystical lake and its guardian." },
    { title: "Chapter 6", desc: "Whispers of a hidden treasure map." },
    { title: "Chapter 7", desc: "Trials in the mountains of despair." },
    { title: "Chapter 8", desc: "A betrayal among friends." },
    { title: "Chapter 9", desc: "The lost city of gold." },
    { title: "Chapter 10", desc: "Facing the shadow beast." },
    { title: "Chapter 11", desc: "Revelations in the grand library." },
    { title: "Chapter 12", desc: "The prophecy comes to light." },
    { title: "Chapter 13", desc: "Gathering allies for the final battle." },
    { title: "Chapter 14", desc: "A perilous journey through the underworld." },
    { title: "Chapter 15", desc: "Confronting the tyrant king." },
    { title: "Chapter 16", desc: "Unveiling the artifact's true power." },
    { title: "Chapter 17", desc: "Sacrifice and redemption." },
    { title: "Chapter 18", desc: "The epic conclusion to the adventure." },
  ];